### ISSUE TITLE
Gala Suit DEF is wrong.

### ISSUE THREAD

**Issue by Diskmaster** [TanukiSharp/MHArmory#19]
Reference https://github.com/AthenaADP/MHW-ASS/issues/12

Relevant cherry pick is https://github.com/AthenaADP/MHW-ASS/commit/763bad8cf741b0e7b707ce80905f20892819b2ba or just

**Comment by TanukiSharp** [comment]
Hello,

I saw your issue on Athena's GitHub, thanks for reporting :)
It's fixed here as well, will be available in the next release.

In the meantime, fell free to fix your local data.

**Comment by TanukiSharp** [comment]
@Diskmaster 

I usually don't close issues on behalf of people, so could you please confirm this is fixed and close the issue, or let me know if it's still a wrong value ?

Thanks,

**Comment by Diskmaster** [comment]
Just checked the values in Equipment explorer as of 0.0.9.6, DEF values appear correct for the part that was mentioned. Thanks.
