### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by lyuha** [TanukiSharp/MHArmory#21]
Launch program occures an error.

FileLoadException : not load Newtonsoft.Json

[2019-06-10_07-25-56_021.log](https://github.com/TanukiSharp/MHArmory/files/3271007/2019-06-10_07-25-56_021.log)

**Comment by TanukiSharp** [comment]
Thank you very much for reporting the problem.
I fixed the bug and made a new version 0.0.9.6.
Sincerely sorry for the troubles.

Once you confirm version 0.0.9.6 works, please close the issue, or added more information if you still have problems.

Thanks.

**Comment by TanukiSharp** [comment]
@lyuha If you confirmed this works for you now, could you close the issue please ?
If you still encounter issue, please let me know.

Thanks.

**Comment by lyuha** [comment]
Thanks to fix.
