### ISSUE TITLE
Event Quest Window Removal

### ISSUE THREAD

**Issue by xaviex** [TanukiSharp/MHArmory#4]
Removal of the events quest window makes it significantly more difficult for PC Users to do armor set searches with only what has been released on PC, before I could just turn off the events that have not been released, now I have to go through and search for every piece of armor in the armor override that has not been released for PC yet and disable it, this may be more accurate, but it still feels like removed functionality

**Comment by TanukiSharp** [comment]
Thank you for your input.

I understand your point, the fact is that it is very hard to keep up with all the events and for which platform, and which equipment they reference.

What I can advice you is simply use the save import features, in this case, no matter what event you already did, it will select what you have. This is the best accuracy you can ever have, in a few clicks.

If you do not want to use the import feature, then you can filter out a set by typing its name, and then clicking the narrow button in from of the equipment buttons in order to toggle them all at once.

Sorry for the inconvenience, but I still feel this is an overall gain.

Let me know if you still have concerns or questions.

**Comment by xaviex** [comment]
I very much understand the difficulty of keeping up with an ever-changing set of spec's in a code-base, though I know a large number of people use armor set finders like this one to find armor that they need to make in order to get the skills they prefer, In this case the save import really is not going to be that useful as the user would not own the items, and they would be excluded on save import (though I will say it is fantastically useful for searching within already created armor) what I might suggest is some way of possibly saving sets of armor exclusions so that they could be user created once than saved (I am sorry if this already exists!) though I really am having trouble thinking of a way to do this cleanly. I would be happy to provide feedback to any other solution you may have, and if I have some free time maybe toss a pull request over

**Comment by xaviex** [comment]
> 
> 
> I very much understand the difficulty of keeping up with an ever-changing set of spec's in a code-base, though I know a large number of people use armor set finders like this one to find armor that they need to make in order to get the skills they prefer, In this case the save import really is not going to be that useful as the user would not own the items, and they would be excluded on save import (though I will say it is fantastically useful for searching within already created armor) what I might suggest is some way of possibly saving sets of armor exclusions so that they could be user created once than saved (I am sorry if this already exists!) though I really am having trouble thinking of a way to do this cleanly. I would be happy to provide feedback to any other solution you may have, and if I have some free time maybe toss a pull request over

**Comment by xaviex** [comment]
My bad on that!

**Comment by TanukiSharp** [comment]
Thanks you for your feedback.

I have to admit your use case sounds perfectly legit and that I never though about that. It makes totally sense.

The idea of having (being able to make) exclusion presets is very good, but also requires a lot of UI work. 

The point I wanted to emphasis with the equipment override replacing the events window is that clicking on that:

![image](https://user-images.githubusercontent.com/4018313/49376408-76f1d180-f74a-11e8-8421-df6dff374738.png)

is strictly equivalent of clicking on that:

![image](https://user-images.githubusercontent.com/4018313/49376436-8f61ec00-f74a-11e8-8c53-2c7d1d3060e2.png)

I hope you understand that adding more feature for even finer grain equipment selection and toggling represent a too big amount of work, and that the current equipment override feature can be satisfying enough.

**Comment by xaviex** [comment]
No problem! I might make a fork and see if I can come up with anything!

**Comment by TanukiSharp** [comment]
Pull requests are welcome if the work is correctly done.

The community would appreciate your efforts :)

**Comment by TanukiSharp** [comment]
Note that [version 0.0.8.1](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0081-20181213) have `Select all` and `Unselect all` buttons, if that can help a bit with the tweaking.

**Comment by xaviex** [comment]
> 
> 
> Note that [version 0.0.8.1](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0081-20181213) has `Select all` and `Unselect all` buttons, if that can help a bit with the tweaking.

This makes this significantly easier to cleanup post first launch

**Comment by TanukiSharp** [comment]
Hi @xaviex 

Any news about a possible PR ?

**Comment by xaviex** [comment]
Hey! Sorry got very busy with work and some home things, haven't had the
time for personal projects lately

**Comment by TanukiSharp** [comment]
Sorry but I close this, since it's been more than 1 year now. If you find time, feel free to re-open or create a new issue.
