### ISSUE TITLE
Kulve armor

### ISSUE THREAD

**Issue by Fatmice** [TanukiSharp/MHArmory#7]
Just want to mention that armor value for all of Kulve's gear is 92.  Cheers.

**Comment by TanukiSharp** [comment]
Thank you for the info. I will check, fix if need be, and let you know here when done.

**Comment by TanukiSharp** [comment]
Indeed the defense values of Kulve Taroth armor pieces were wrong, all of them (base, max and augmented max) ^^

Thank you very much for reporting, fixed in commit 6abbe281d187101b4127662f492674eef8c57fe8 and will be available on next release (0.0.8.3 presumably)
