### ISSUE TITLE
Search optimization

### ISSUE THREAD

**Issue by Fatmice** [TanukiSharp/MHArmory#8]
Okay I'm back with an example where a search that should give result but instead gave nothing.
![image](https://user-images.githubusercontent.com/8956281/50239599-43d55200-0388-11e9-8dad-893f7ae85afa.png)
Here we are searching for 
Botanist Lv3 Detector Lv1 Forager’s Luck Lv1 Geologist Lv3 Intimidator Lv3 Master Gatherer Lv1 Scent Hound Lv1 Scholar Lv1 Tool Specialist Lv3 Effluvial Expert Lv1 Heat Guard Lv1
This should give exactly 1 match given restrictions on PC sets (excluding Drachen a, Kush y, Kaiser y, Zorah y, Xeno y, Luna y, spring event, summer event, Azure Starlord a...)
as found by [http://mhw.wiki-db.com](http://mhw.wiki-db.com/sim/?hl=en#skills=Botanist%20Lv3,Detector%20Lv1,Forager%E2%80%99s%20Luck%20Lv1,Geologist%20Lv3,Intimidator%20Lv3,Master%20Gatherer%20Lv1,Scent%20Hound%20Lv1,Scholar%20Lv1,Tool%20Specialist%20Lv3,Effluvial%20Expert%20Lv1,Heat%20Guard%20Lv1&w=LV1-1-1%20Slot%20Weapon&g=20&s=1&l=200&d=0&rf=-100&rw=-100&rt=-100&ri=-100&rd=-100)
![image](https://user-images.githubusercontent.com/8956281/50239756-9d3d8100-0388-11e9-9cd4-7ff7b9907aab.png)

**Comment by TanukiSharp** [comment]
Thank you very much for reporting this. I will have a look as soon as I can and keep you posted :)

**Comment by Fatmice** [comment]
I have the King Beetle but not the Queen Beetle sets.
![image](https://user-images.githubusercontent.com/8956281/50313172-27ace000-0470-11e9-8c70-19fbdf5c1f9a.png)

**Comment by Fatmice** [comment]
Oh hoh, I found what the issue was.  Gender needed to be changed to "Male" only.  In this case, the King and Queen Beetle are not the same thing even though they are seems like "male/female" of the armor set.  Database tweak is needed? Also on save import, maybe also change the gender?  Cheers.

**Comment by TanukiSharp** [comment]
Not sure about importing the gender, it's a bit overkill and I prefer user to set it themselves. It is persisted in user settings so you have to set it only once.

The real problem is more like why when setting gender to both, it does work, this is a real problem I will investigate. When setting both, you should have two results (one with King and one with Queen) instead of zero.

**Comment by TanukiSharp** [comment]
I've spotted and fixed wrong gender processing bug. So now selected male or female works as before, but selecting both now works as expected.

Note that the amount of combinations grows rapidly, but now when setting both it indeed finds the two sets.

Fixed in commit e8285f6bca2c44fcad0b5ada6d579e9b9103cd19 and will be included in the next release.

**Comment by Fatmice** [comment]
The King Beetle is for male and its equivalent is Butterfly for female. This set is gotten from getting a Great Hornfly from cultivating.  This  set is unrelated to the Queen Beetle (female) and its equivalent Butterfly (male)

**Comment by TanukiSharp** [comment]
According to this page https://monsterhunterworld.wiki.fextralife.com/King+Beetle+Armor+Set it seems what you say is correct. Mixing sets this way doesn't really makes sense to me, but whatever ^^

Do you confirm the algorithm works correctly when setup correctly ? Or do you still have issues ?

**Comment by Fatmice** [comment]
Algorithm is working correctly when setting up the gender correctly.

**Comment by TanukiSharp** [comment]
Version 0.0.8.3 has been released which addresses this issue. now setting gender to **both** works as expected. Sorry for the troubles.

See [change log here](https://github.com/TanukiSharp/MHArmory/blob/master/ChangeLog.md#0083-20181222).

**Comment by Fatmice** [comment]
Working now.
